"""LOCALOCR web-UI package (Phase 3).

Exposes the :func:`create_app` factory used by ``python -m src.web``
and by the test suite. Nothing outside this package should reach into
``src.web.services.*`` -- the FastAPI app is the public surface.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles

from .routes import progress, runs, videos
from .services.db import init_db


def create_app(db_path: Optional[Path] = None) -> FastAPI:
    """Build a fresh FastAPI app instance.

    Kept as a factory (not a module-level global) so tests can spin
    up isolated apps with their own tmp SQLite files.

    Mounts:
      - ``/`` + ``/runs*`` -- routes.runs
      - ``/videos*``       -- routes.videos
      - ``/output``        -- output directory (frame thumbnails, viewer.html)
      - ``/static``        -- src/web/static (JS/CSS added in 03-04)
      - ``/health``        -- liveness probe (JSON)
    """
    app = FastAPI(title="LOCALOCR", version="1.1")
    app.state.db_path = db_path or Path("output/localocr.sqlite").resolve()
    init_db(app.state.db_path)

    app.include_router(runs.router)
    app.include_router(videos.router)
    app.include_router(progress.router)

    # Serve output/ so pick cards can link to matched frame thumbnails
    # AND so the standalone viewer.html generated by post_ocr_pipeline
    # remains reachable at /output/viewer.html.
    output_dir = Path("output").resolve()
    if output_dir.exists():
        app.mount("/output", StaticFiles(directory=str(output_dir)), name="output")

    # Serve src/web/static (populated in plan 03-04 with the seek JS,
    # SSE client bridge, etc.). Optional so plans 03-01..03-03 don't
    # require the directory to exist.
    static_dir = Path(__file__).resolve().parent / "static"
    if static_dir.exists():
        app.mount("/static", StaticFiles(directory=str(static_dir)), name="static")

    @app.get("/health")
    def health() -> dict:
        return {"status": "ok", "db_path": str(app.state.db_path)}

    return app
